[package]
name = "eql_parser"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
cfg-if = "1.0.0"
indexmap = { workspace = true }

[dev-dependencies]
insta.workspace = true
