[package]
name = "maso_router_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = "1.0.102"
walkdir = "2.3.2"

[lib]
proc-macro = true
