[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
styled-yew = "0.3.0"
yew = { git = "https://github.com/yewstack/yew", features = ["ssr", "hydration"] }
yew-router = { git = "https://github.com/yewstack/yew" }
